// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAxkeXzmkqs9weIrihjHrIEpR-MVYaDWNs',
    appId: '1:505962464441:android:1dc09a9d4a91af91740768',
    messagingSenderId: '505962464441',
    projectId: 'ivy-wardrobe',
    databaseURL: 'https://ivy-wardrobe-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'ivy-wardrobe.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCsAsfmlVr-E-IomxnZu5mG0PkjOySFffM',
    appId: '1:505962464441:ios:6666382f2098f0f6740768',
    messagingSenderId: '505962464441',
    projectId: 'ivy-wardrobe',
    databaseURL: 'https://ivy-wardrobe-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'ivy-wardrobe.firebasestorage.app',
    iosBundleId: 'com.example.wardobeApp',
  );
}
